### ISSUE TITLE
WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

### ISSUE THREAD

**Issue by niemyjski** [Gibbu/svoast#8] opened 2023-12-15 02:03 UTC
https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition

**Comment by Nicicalu** [comment] 2023-12-18 13:21
This needs to be added to package.json:
```
"exports": {
   ".": {
     "svelte": "./index.js"
   }
 }
```

**Comment by niemyjski** [comment] 2023-12-26 17:35
@Nicicalu can you add a pr for this?

**Comment by Nicicalu** [comment] 2023-12-26 19:49
@niemyjski I just saw it's already there:
https://github.com/Gibbu/svoast/blob/7c77233f4fc51f1ce92d9d260bdd6a71f64bdbdc/package.json#L74
The problem is, that the `package.json` that is on npm seems to be different:
https://www.npmjs.com/package/svoast/v/2.3.0?activeTab=code

**Comment by Gibbu** [comment] 2023-12-27 05:02
Yeah sorry about that. The last couple weeks have been hectic.
I had enough free time to push an update to github, but not too sure how to push an update to npm with `svelte-package@^2` without pushing the entire repo.

**Comment by Gibbu** [comment] 2024-01-22 06:57
Wasn't meant to close this.

I pretty much just copied the old generation of `svelte-package`.
The latest version (`@2.4.2`) *should* fix this issue.

**Comment by Nicicalu** [comment] 2024-01-22 08:36
Thank you! I'll try it out

**Comment by Nicicalu** [comment] 2024-01-22 18:05
Warning is gone now, thank you very much!
Can be closed IMO

**Comment by Nicicalu** [comment] 2024-01-22 21:53
I think you've deleted the types, now typescript can't find the types for `svoast`
![image](https://github.com/Gibbu/svoast/assets/52490746/d21dc8ad-a9a7-48e8-8e4d-f5e055c923cf)

**Comment by Gibbu** [comment] 2024-01-24 00:10
Weird... It should work. I've added `typedVersions` to the `package.json` in the latest version: `@2.4.3`

**Comment by Nicicalu** [comment] 2024-01-24 10:48
@Gibbu Still the same issue...
![image](https://github.com/Gibbu/svoast/assets/52490746/4ffb9dcb-a86c-4765-afbc-918bb7df0e9c)

**Comment by Gibbu** [comment] 2024-01-25 09:45
Ah ha! I've figured it out. 
I had to add a `"types": "./index.d.ts"` to the vite default export.

There isn't anything pointing to the reason on the [vite docs](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-conditio) as linked in the original message.

**Comment by Nicicalu** [comment] 2024-01-25 16:00
@Gibbu  Works now, thank you very much! 
Issue can be closed IMO :-)

**Closed as completed** 2024-01-25 21:41 UTC
